# Generated by Django 4.2.4 on 2023-09-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-04-22'),
            preserve_default=False,
        ),
    ]
